#
# Copyright (c) 2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
name: Validate Devfiles

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Minikube
      uses: manusa/actions-setup-minikube@v2.3.1
      with:
        minikube version: 'v1.16.0'
        kubernetes version: 'v1.19.2'
    - name: Setup Go environment
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
    - name: Checkout odo repo
      uses: actions/checkout@v2
      with:
        repository: openshift/odo
        path: odo
    - name: Build odo
      run: cd odo && make && chmod +x ./odo && cp ./odo ../odo-binary
    - name: Test odo
      run: ls && ./odo-binary
    - name: Validate the devfile stacks
      run: .ci/test.sh ./odo-binary 
